<?php

namespace AppBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllBrandsOrderedByType(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('b')
            ->from('AppBundle:Brand','b')
            ->innerJoin('b.type','t')
            ->orderBy('t.name','ASC')
        ;

        return $qb->getQuery()->getResult();
    }
}
