<?php

namespace AppBundle\Repository;

/**
 * DistributionIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionIRepository extends \Doctrine\ORM\EntityRepository
{
}
