<?php

namespace AppBundle\Repository;

/**
 * DistributionERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionERepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllDistributionsE($filter=null){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('d')
            ->from('AppBundle:DistributionE','d')
            ->innerJoin('d.hotel','h');

            if($filter!=""){
                $qb
                    ->innerJoin('d.equipments', 'e')
                    ->innerJoin('e.model','m')
                    ->innerJoin('m.brand','b')
                    ->innerJoin('b.type','t')
                    ->where($qb->expr()->like('d.requestDate', '?1'))
                    ->orWhere($qb->expr()->like('h.name', '?1'))
                    ->orWhere($qb->expr()->like('e.ni', '?1'))
                    ->orWhere($qb->expr()->like('e.ns', '?1'))
                    ->orWhere($qb->expr()->like('e.description', '?1'))
                    ->orWhere($qb->expr()->like('m.name', '?1'))
                    ->orWhere($qb->expr()->like('b.name', '?1'))
                    ->orWhere($qb->expr()->like('t.name', '?1'))
    //                    ->orWhere($qb->expr()->like('e.ni', '?1'))
                    ->setParameter(1, '%' . $filter . '%');
            }

        $qb->orderBy('h.name','DESC');

        $result = $qb->getQuery()/*->getResult()*/;
        return $result;
    }
}
