<?php

namespace AppBundle\Repository;

/**
 * DistributionERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionERepository extends \Doctrine\ORM\EntityRepository
{
}
