<?php

namespace AppBundle\Repository;

/**
 * EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEquipmentOrderByType($filter=null){
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();
        $qb->select('e')
            ->from('AppBundle:Equipment','e')
            ->innerJoin('e.model','m')
            ->innerJoin('m.brand','b')
            ->innerJoin('b.type','t')
        ;
        if($filter!="") {
            $qb
                ->where($qb->expr()->like('e.createAt', '?1'))
                ->orWhere($qb->expr()->like('e.description', '?1'))
                ->orWhere($qb->expr()->like('e.ni', '?1'))
                ->orWhere($qb->expr()->like('e.ns', '?1'))
                ->orWhere($qb->expr()->like('m.name', '?1'))
                ->orWhere($qb->expr()->like('b.name', '?1'))
                ->orWhere($qb->expr()->like('t.name', '?1'))
                ->setParameter(1, '%' . $filter . '%')
            ;
        }

        $qb->andWhere('e.movement is null');
        $qb->andWhere('e.distribution is null');
        $result = $qb->getQuery()/*->getResult()*/;
        return $result;
    }
}
