<?php

namespace AppBundle\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllHotelsOrderedByName(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('h')
            ->from('AppBundle:Hotel','h')
            ->orderBy('h.name','ASC');
        return $qb->getQuery()->getResult();
    }
}
