<?php

namespace AppBundle\Repository;

/**
 * InstalationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstalationRepository extends \Doctrine\ORM\EntityRepository
{
}
