<?php

namespace AppBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllInvoicesOrderedByDate(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('i')
            ->from('AppBundle:Invoice','i')
            ->orderBy('i.date','DESC');
        return $qb->getQuery()/*->getResult()*/;
    }
}
