<?php

namespace AppBundle\Repository;

/**
 * MERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MERepository extends \Doctrine\ORM\EntityRepository
{
}
