<?php

namespace AppBundle\Repository;

/**
 * MERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MERepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllMovementsOrderByDate(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('m')
            ->from('AppBundle:ME','m')
            ->innerJoin('m.hotel','h')
        ;
        return $qb->getQuery();
    }
}
