<?php

namespace AppBundle\Repository;

/**
 * MIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MIRepository extends \Doctrine\ORM\EntityRepository
{
}
