<?php

namespace AppBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllPersonOrderedByDepartment(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('p')
            ->from('AppBundle:Person','p')
            ->innerJoin('p.department','d')
            ->orderBy('d.name','ASC')
        ;

        return $qb->getQuery();
    }
}
