# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db:
            entity:
                class: AppBundle\Entity\User
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: db
            pattern: ^/

            form_login:
                login_path: login
                check_path: login
#                default_target_path: movement_index

            logout:
                path:   /logout
                target: login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*, roles: [ROLE_ADMIN]}
        - { path: ^/distributione/new*, roles: [ROLE_DIRECTOR]}
        - { path: ^/distributione/edit/*, roles: [ROLE_DIRECTOR]}
        - { path: ^/distributione/delete/*, roles: [ROLE_DIRECTOR]}